apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  strategy:
    blueGreen:
      activeService: develop-frontend-service
      previewService: develop-frontend-service-preview
      autoPromotionEnabled: false
  template:
    metadata:
      labels:
        app: frontend-pod
        project: banking
    spec:
      containers:
        - name: frontend
          image: bilal690/banking-frontend:0.0.6.develop
          ports:
            - containerPort: 3000
