apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rest-accounts
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: develop
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: testbed/rest-services/accounts/develop
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}