apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-gateway 
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: HEAD
    path: testbed/istio/gateway

  destination:
    namespace: banking-gateway
    server: {{ .Values.spec.destination.server }}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    validate: true
