---
apiVersion: v1
kind: Namespace
metadata:
  name: develop
  labels:
    name: "develop"
    istio-injection: "enabled"
---
apiVersion: v1
kind: Namespace
metadata:
  name: banking-gateway
  labels:
    name: "banking-gateway"
    istio-injection: "enabled"
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
