apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: transactions
  labels:
    app: transactions
spec:
    blueGreen:
      activeService: develop-transactions-service
      previewService: develop-transactions-service-preview
      autoPromotionEnabled: false
    template:
      spec:
        containers:
        - name: transactions
          image: bilal690/banking-transactions:0.3.develop
          ports:
          - containerPort: 3000
          startupProbe:
            httpGet:
              path: /healthz
              port: 3000
            failureThreshold: 5
            periodSeconds: 3
          env:
            - name: ACCOUNTS_SERVICE_URL
              value: http://develop-accounts-service
            - name: TESTDATA_SERVICE_URL
              value: http://develop-testdata-service