apiVersion: apps/v1
kind: Deployment
metadata:
  name: testdata
spec:
  template:
    spec:
      containers:
        - name: testdata
          image: docker.io/bilal690/dockerhub:0.1.develop
          ports:
          - containerPort: 3000
