apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "testdata"
  namespace: argocd # Should match the namespace Argo CD is running on
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: kustomize-testdata\develop
    repoURL: https://github.com/Bilaltariq98/k8s-banking-testbed-argocd.git
    targetRevision: develop
  destination:
    namespace: develop
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
