apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
    replicas: 2
    selector:
      matchLabels:
        app: frontend-pod
    template:
      metadata:
        labels:
          app: frontend-pod
          project: banking
      spec:
        containers:
        - name: frontend
          image: k3d-banking-registry:5000/banking-frontend:local
          ports:
          - containerPort: 3000