apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: contacts
  labels:
    app: contacts
spec:
    replicas: 3
    selector:
      matchLabels:
        app: contacts-pod
    strategy:
      blueGreen:
        activeService: contacts-service
        previewService: contacts-service-preview
        autoPromotionEnabled: false
    template:
      metadata:
        labels:
          app: contacts-pod
          project: banking
      spec:
        containers:
        - name: contacts
          image: k3d-banking-registry:5000/banking-contacts:local
          ports:
          - containerPort: 3000
          startupProbe:
            httpGet:
              path: /healthz
              port: 3000
            failureThreshold: 5
            periodSeconds: 3