apiVersion: v1
kind: Service
metadata:
  labels:
    app: contacts
  name: contacts-preview
spec:
  ports:
  - port: 80
    targetPort: 3000
    appProtocol: http
  selector:
    app: contacts-pod
  type: ClusterIP
