apiVersion: v1
kind: Service
metadata:
  name: rollouts-service
  namespace: argocd
  labels:
    app: rollouts
spec:
  ports:
  - port: 80
    targetPort: 3000
    appProtocol: http
  selector:
    app: rollouts-pod
  type: ClusterIP