apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: monitoring
  namespace: operations
  labels:
    app: monitoring
spec:
    replicas: 2
    selector:
      matchLabels:
        app: monitoring-pod
    strategy:
      blueGreen:
        activeService: monitoring-service
        previewService: monitoring-service-preview
        autoPromotionEnabled: false
    template:
      metadata:
        labels:
          app: monitoring-pod
          project: banking
      spec:
        serviceAccountName: monitoring-account
        containers:
        - name: monitoring
          image: k3d-banking-registry:5000/banking-monitoring:local
          ports:
          - containerPort: 3000