apiVersion: v1
kind: Service
metadata:
  name: monitoring-service-preview
  namespace: operations
  labels:
    app: monitoring
spec:
  ports:
  - port: 80
    targetPort: 3000
    appProtocol: http
  selector:
    app: monitoring-pod
  type: ClusterIP