apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer
  labels:
    app: customer
spec:
    replicas: 3
    selector:
      matchLabels:
        app: customer-pod
    template:
      metadata:
        labels:
          app: customer-pod
          project: banking
      spec:
        containers:
        - name: customer
          image: bilal690/banking-customer:latest
          ports:
          - containerPort: 3000
          startupProbe:
            httpGet:
              path: /healthz
              port: 3000
            failureThreshold: 5
            periodSeconds: 3