apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: customer
  labels:
    app: customer
spec:
  strategy:
    blueGreen:
      activeService: develop-customer-service
      previewService: develop-customer-service-preview
      autoPromotionEnabled: false
  template:
    spec:
      containers:
        - name: customer
          image: bilal690/banking-customer:0.0.4.develop
          ports:
            - containerPort: 3000
          startupProbe:
            httpGet:
              path: /healthz
              port: 3000
            failureThreshold: 5
            periodSeconds: 3
          env:
            - name: ACCOUNTS_SERVICE_URL
              value: http://develop-accounts-service
            - name: CONTACTS_SERVICE_URL
              value: http://develop-contacts-service
            - name: TESTDATA_SERVICE_URL
              value: http://develop-testdata-service
            - name: KAFKA_TOPIC_NAME
              value: customer
            - name: BROKER_URL
              value: 172.20.0.2:32248
