apiVersion: v1
kind: Service
metadata:
  labels:
    app: transactions
  name: transactions-service-preview
spec:
  ports:
  - port: 80
    targetPort: 3000
    appProtocol: http
  selector:
    app: transactions-pod
  type: ClusterIP
