apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring
  namespace: operations
  labels:
    app: monitoring
spec:
  replicas: 2
  selector:
    matchLabels:
      app: monitoring-pod
  template:
    metadata:
      labels:
        app: monitoring-pod
        project: banking
    spec:
      serviceAccountName: monitoring-account
      containers:
        - name: monitoring
          image: bilal690/banking-monitoring:0.0.2.develop
          ports:
            - containerPort: 3000
          env:
            - name: FRONTEND_SERVICE_DNS
              value: develop-frontend-service.develop.svc.cluster.local
            - name: APP_NAMESPACE
              value: develop
