apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: monitoring
  namespace: operations
  labels:
    app: monitoring
spec:
    strategy:
      blueGreen:
        activeService: develop-monitoring-service
        previewService: develop-monitoring-service-preview
        autoPromotionEnabled: false
    template:
      metadata:
        labels:
          app: monitoring-pod
          project: banking
      spec:
        serviceAccountName: monitoring-account
        containers:
        - name: monitoring
          image: bilal690/banking-monitoring:0.3.develop
          ports:
          - containerPort: 3000
          env:
            - name: FRONTEND_SERVICE_DNS
              value: develop-frontend-service.develop.svc.cluster.local
            - name: APP_NAMESPACE
              value: develop