apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts
  labels:
    app: accounts
spec:
    replicas: 3
    selector:
      matchLabels:
        app: accounts-pod
    template:
      metadata:
        labels:
          app: accounts-pod
          project: banking
      spec:
        containers:
        - name: accounts
          image: bilal690/banking-accounts:0.2.develop
          ports:
          - containerPort: 3000
          startupProbe:
            httpGet:
              path: /healthz
              port: 3000
            failureThreshold: 5
            periodSeconds: 3
          env:
            - name: CUSTOMER_SERVICE_URL
              value: http://localhost:8080/customers
            - name: TRANSACTIONS_SERVICE_URL
              value: http://localhost:8080/transactions
            - name: TESTDATA_SERVICE_URL
              value: http://localhost:8080/testdata