apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: accounts
  labels:
    app: accounts
spec:
    replicas: 3
    selector:
      matchLabels:
        app: accounts-pod
    strategy:
      blueGreen:
        activeService: accounts-service
        previewService: accounts-service-preview
        autoPromotionEnabled: false
    template:
      metadata:
        labels:
          app: accounts-pod
          project: banking
      spec:
        containers:
        - name: accounts
          image: k3d-banking-registry:5000/banking-accounts:local
          ports:
          - containerPort: 3000
          startupProbe:
            httpGet:
              path: /healthz
              port: 3000
            failureThreshold: 5
            periodSeconds: 3
