apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: kafka-topic
  labels:
    strimzi.io/cluster: "kafka-cluster"
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  partitions: 3
  replicas: 1