apiVersion: apps/v1
kind: Deployment
metadata:
  name: contacts
  labels:
    app: contacts
spec:
    replicas: 3
    selector:
      matchLabels:
        app: contacts-pod
    template:
      metadata:
        labels:
          app: contacts-pod
          project: banking
      spec:
        containers:
        - name: contacts
          image: bilal690/banking-contacts:0.3.develop
          ports:
          - containerPort: 3000
          startupProbe:
            httpGet:
              path: /healthz
              port: 3000
            failureThreshold: 5
            periodSeconds: 3
          env:
            - name: CUSTOMER_SERVICE_URL
              value: http://develop-customer-service
            - name: TESTDATA_SERVICE_URL
              value: http://develop-testdata-service